name: Melpazoid

on: [push, pull_request]

jobs:
  melpazoid:
    strategy:
      matrix:
        emacs_version: ['28.1', '28.2', '29.1']
           
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Melpazoid
      run: |
        python -m pip install --upgrade pip
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        pip install ~/melpazoid

    - Name: Check Package
      env:
        LOCAL_REPO: ${{ github.workspace }}
        RECIPE: (sdml-fold :fetcher github :repo "sdm-lang/emacs-sdml-fold" :files ("sdml-fold.el"))
        # set this to false (or remove it) if the package isn't on MELPA:
        EXIST_OK: false
      run: |
        echo $GITHUB_REF
        make -C ~/melpazoid
